# Generated by Django 5.1.6 on 2025-05-04 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='mfg_date',
            field=models.DateField(null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pack_size',
            field=models.CharField(help_text="e.g., '1 Kg', '500 g', '2L'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Enter a discount between 1 and 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
