# Generated by Django 5.1.6 on 2025-05-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel'),
        ),
    ]
