# Generated by Django 5.1.6 on 2025-05-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_categorymodel_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='product_category',
        ),
    ]
